name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set date
      id: set_date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/podcast-proxy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/podcast-proxy:${{ github.run_id }}
          ${{ secrets.DOCKERHUB_USERNAME }}/podcast-proxy:${{ env.DATE }} 
        platforms: linux/amd64,linux/arm64

